CLASS zbp_i_demo_materialdocument DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_demo_materialdocument.

PUBLIC SECTION.
CLASS-DATA cv_matdoc_mapped TYPE RESPONSE FOR MAPPED i_materialdocumenttp.

ENDCLASS.



CLASS ZBP_I_DEMO_MATERIALDOCUMENT IMPLEMENTATION.
ENDCLASS.
