CLASS zbp_i_demo_outbound_api DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_demo_outbound_api.

    PUBLIC SECTION.
    CLASS-DATA cv_matdoc_mapped TYPE RESPONSE FOR MAPPED i_materialdocumenttp.

ENDCLASS.



CLASS ZBP_I_DEMO_OUTBOUND_API IMPLEMENTATION.
ENDCLASS.
