@EndUserText.label: 'Demo MaterialDocumentItem'
@AccessControl.authorizationCheck: #NOT_REQUIRED
@Metadata.allowExtensions: true
define view entity ZC_Demo_MaterialDocumentItem as projection on ZI_Demo_MaterialDocumentItem
{
    key MaterialDocumentYear,
    key MaterialDocument,
    key MaterialDocumentItem,
    Material,
    Plant,
    StorageLocation,
    StorageType,
    StorageBin,
    Batch,
    ShelfLifeExpirationDate,
    ManufactureDate,
    Supplier,
    SalesOrder,
    SalesOrderItem,
    SalesOrderScheduleLine,
    WBSElementInternalID,
    Customer,
    InventorySpecialStockType,
    InventoryStockType,
    StockOwner,
    GoodsMovementType,
    DebitCreditCode,
    InventoryUsabilityCode,
    QuantityInBaseUnit,
    MaterialBaseUnit,
    QuantityInEntryUnit,
    EntryUnit,
    PostingDate,
    DocumentDate,
    TotalGoodsMvtAmtInCCCrcy,
    CompanyCodeCurrency,
    InventoryValuationType,
    ReservationIsFinallyIssued,
    PurchaseOrder,
    PurchaseOrderItem,
    ProjectNetwork,
    OrderID,
    OrderItem,
    MaintOrderRoutingNumber,
    MaintOrderOperationCounter,
    Reservation,
    ReservationItem,
    DeliveryDocument,
    DeliveryDocumentItem,
    ReversedMaterialDocumentYear,
    ReversedMaterialDocument,
    ReversedMaterialDocumentItem,
    RvslOfGoodsReceiptIsAllowed,
    GoodsRecipientName,
    UnloadingPointName,
    CostCenter,
    GLAccount,
    ServicePerformer,
    PersonWorkAgreement,
    AccountAssignmentCategory,
    WorkItem,
    ServicesRenderedDate,
    IssgOrRcvgMaterial,
    IssuingOrReceivingPlant,
    IssuingOrReceivingStorageLoc,
    IssgOrRcvgBatch,
    IssgOrRcvgSpclStockInd,
    CompanyCode,
    BusinessArea,
    ControllingArea,
    FiscalYearPeriod,
    FiscalYearVariant,
    GoodsMovementRefDocType,
    IsCompletelyDelivered,
    MaterialDocumentItemText,
    IsAutomaticallyCreated,
    GoodsReceiptType,
    ConsumptionPosting,
    MultiAcctAssgmtOriglMatlDocItm,
    MultipleAccountAssignmentCode,
    GoodsMovementIsCancelled,
    IssuingOrReceivingStockType,
    /* Associations */
    _MaterialDocument : redirected to parent ZC_Demo_MaterialDocument
}
