@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Demo MaterialDocumentItem'
define view entity ZI_Demo_MaterialDocumentItem as 
select from I_MaterialDocumentItem_2 as _MaterialDocumentItem
association to parent ZI_Demo_MaterialDocument as _MaterialDocument
    on $projection.MaterialDocumentYear = _MaterialDocument.MaterialDocumentYear and
    $projection.MaterialDocument = _MaterialDocument.MaterialDocument
{
    key _MaterialDocumentItem.MaterialDocumentYear,
    key _MaterialDocumentItem.MaterialDocument,
    key _MaterialDocumentItem.MaterialDocumentItem,
    _MaterialDocumentItem.Material,
    _MaterialDocumentItem.Plant,
    _MaterialDocumentItem.StorageLocation,
    _MaterialDocumentItem.StorageType,
    _MaterialDocumentItem.StorageBin,
    _MaterialDocumentItem.Batch,
    _MaterialDocumentItem.ShelfLifeExpirationDate,
    _MaterialDocumentItem.ManufactureDate,
    _MaterialDocumentItem.Supplier,
    _MaterialDocumentItem.SalesOrder,
    _MaterialDocumentItem.SalesOrderItem,
    _MaterialDocumentItem.SalesOrderScheduleLine,
    _MaterialDocumentItem.WBSElementInternalID,
    _MaterialDocumentItem.Customer,
    _MaterialDocumentItem.InventorySpecialStockType,
    _MaterialDocumentItem.InventoryStockType,
    _MaterialDocumentItem.StockOwner,
    _MaterialDocumentItem.GoodsMovementType,
    _MaterialDocumentItem.DebitCreditCode,
    _MaterialDocumentItem.InventoryUsabilityCode,
    _MaterialDocumentItem.QuantityInBaseUnit,
    _MaterialDocumentItem.MaterialBaseUnit,
    _MaterialDocumentItem.QuantityInEntryUnit,
    _MaterialDocumentItem.EntryUnit,
    _MaterialDocumentItem.PostingDate,
    _MaterialDocumentItem.DocumentDate,
    _MaterialDocumentItem.TotalGoodsMvtAmtInCCCrcy,
    _MaterialDocumentItem.CompanyCodeCurrency,
    _MaterialDocumentItem.InventoryValuationType,
    _MaterialDocumentItem.ReservationIsFinallyIssued,
    _MaterialDocumentItem.PurchaseOrder,
    _MaterialDocumentItem.PurchaseOrderItem,
    _MaterialDocumentItem.ProjectNetwork,
    _MaterialDocumentItem.OrderID,
    _MaterialDocumentItem.OrderItem,
    _MaterialDocumentItem.MaintOrderRoutingNumber,
    _MaterialDocumentItem.MaintOrderOperationCounter,
    _MaterialDocumentItem.Reservation,
    _MaterialDocumentItem.ReservationItem,
    _MaterialDocumentItem.DeliveryDocument,
    _MaterialDocumentItem.DeliveryDocumentItem,
    _MaterialDocumentItem.ReversedMaterialDocumentYear,
    _MaterialDocumentItem.ReversedMaterialDocument,
    _MaterialDocumentItem.ReversedMaterialDocumentItem,
    _MaterialDocumentItem.RvslOfGoodsReceiptIsAllowed,
    _MaterialDocumentItem.GoodsRecipientName,
    _MaterialDocumentItem.UnloadingPointName,
    _MaterialDocumentItem.CostCenter,
    _MaterialDocumentItem.GLAccount,
    _MaterialDocumentItem.ServicePerformer,
    _MaterialDocumentItem.PersonWorkAgreement,
    _MaterialDocumentItem.AccountAssignmentCategory,
    _MaterialDocumentItem.WorkItem,
    _MaterialDocumentItem.ServicesRenderedDate,
    _MaterialDocumentItem.IssgOrRcvgMaterial,
    _MaterialDocumentItem.IssuingOrReceivingPlant,
    _MaterialDocumentItem.IssuingOrReceivingStorageLoc,
    _MaterialDocumentItem.IssgOrRcvgBatch,
    _MaterialDocumentItem.IssgOrRcvgSpclStockInd,
    _MaterialDocumentItem.CompanyCode,
    _MaterialDocumentItem.BusinessArea,
    _MaterialDocumentItem.ControllingArea,
    _MaterialDocumentItem.FiscalYearPeriod,
    _MaterialDocumentItem.FiscalYearVariant,
    _MaterialDocumentItem.GoodsMovementRefDocType,
    _MaterialDocumentItem.IsCompletelyDelivered,
    _MaterialDocumentItem.MaterialDocumentItemText,
    _MaterialDocumentItem.IsAutomaticallyCreated,
    _MaterialDocumentItem.GoodsReceiptType,
    _MaterialDocumentItem.ConsumptionPosting,
    _MaterialDocumentItem.MultiAcctAssgmtOriglMatlDocItm,
    _MaterialDocumentItem.MultipleAccountAssignmentCode,
    _MaterialDocumentItem.GoodsMovementIsCancelled,
    _MaterialDocumentItem.IssuingOrReceivingStockType,
    /* Associations */
    _MaterialDocument
}
